### PR TITLE
VBump component version to 23.0.0

### PR DESCRIPTION
**Pull request by hfazai**
This is to support upgrade to V22.0.6 after releasing a new component version.
https://github.com/vaadin-component-factory/vcf-enhanced-dialog/pull/5

Update: now targeting V23.0.0

### CODE REVIEW

**Comment by hfazai** [comment]
@jcgueriaud1 could you please review this?

**Review by jcgueriaud1 — APPROVED** [review]
I will merge this on a branch and update the code. The demo is not running in V23, that need to be bumped

**Comment by hfazai** [comment]
@jcgueriaud1 could you please also release a version for V22, because V23 doesn't support Java 8 and some people will take a time to migrate to Java11 so at the meanwhile they will be able to continue using EnhancedDialog.

**Comment by jcgueriaud1** [comment]
The Vaadin 23 version of the addon has been released.

**Comment by hfazai** [comment]
@jcgueriaud1 Great, Thanks!
And what about V22 are planning to create a release?

**Comment by jcgueriaud1** [comment]
If you need it, I can do it next week but I would rather put my effort in something else.

**Comment by hfazai** [comment]
Yes if that doesn't take you too much time.

Actually I workaround it with extending EnhancedDialog and annotating it with `@NpmPackage(value = "@vaadin-component-factory/vcf-enhanced-dialog", version = "22.0.6")`

It's working fine but has some side effects:
- showing this warning :
`Multiple npm versions for @vaadin-component-factory/vcf-enhanced-dialog found:  [22.0.6, 21.0.0]. First version found '22.0.6' will be considered.`
- And sometimes failing when doing live reload.

**Comment by jcgueriaud1** [comment]
I published a Vaadin 22 version of the component, can you try it and tell me if it's working?

**Comment by hfazai** [comment]
@jcgueriaud1 yup, it works fine thanks 👍

**Pull request merged**
